-- CREATE TABLE roles (
--            id BIGSERIAL PRIMARY KEY,
--            name VARCHAR(50) UNIQUE NOT NULL
-- );
--
-- CREATE TABLE users (
--            id BIGSERIAL PRIMARY KEY,
--            first_name VARCHAR(100) NOT NULL,
--            last_name VARCHAR(100) NOT NULL,
--            email VARCHAR(255) UNIQUE NOT NULL,
--            password VARCHAR(255) NOT NULL,
--            enabled BOOLEAN NOT NULL DEFAULT TRUE,
--            account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
--            created_at TIMESTAMP NOT NULL,
--            updated_at TIMESTAMP NOT NULL
-- );
--
-- CREATE TABLE user_roles (
--                 user_id BIGINT NOT NULL,
--                 role_id BIGINT NOT NULL,
--                 PRIMARY KEY(user_id, role_id),
--                 FOREIGN KEY(user_id) REFERENCES users(id),
--                 FOREIGN KEY(role_id) REFERENCES roles(id)
-- );
--
-- CREATE TABLE refresh_tokens (
--             id BIGSERIAL PRIMARY KEY,
--             token VARCHAR(255) UNIQUE NOT NULL,
--             expiry_date TIMESTAMP NOT NULL,
--             revoked BOOLEAN DEFAULT FALSE,
--             user_id BIGINT NOT NULL,
--             FOREIGN KEY(user_id) REFERENCES users(id)
-- );