INSERT INTO roles (
    uuid,
    name,
    created_at,
    updated_at,
    version
)
VALUES
    (
        gen_random_uuid(),
        'ROLE_USER',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    ),
    (
        gen_random_uuid(),
        'ROLE_ADMIN',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    );